[2024-04-12T00:31:32.132+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T00:31:32.228+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [queued]>
[2024-04-12T00:31:32.239+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [queued]>
[2024-04-12T00:31:32.241+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 7
[2024-04-12T00:31:32.260+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_even_odd> on 2024-04-12 00:29:20.868171+00:00
[2024-04-12T00:31:32.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas1_no2', 'check_even_odd', 'manual__2024-04-12T00:29:20.868171+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/nomer2_dag.py', '--cfg-path', '/tmp/tmpc2sdv43a']
[2024-04-12T00:31:32.276+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask check_even_odd
[2024-04-12T00:31:32.276+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T00:31:32.277+0000] {standard_task_runner.py:63} INFO - Started process 270 to run task
[2024-04-12T00:31:32.335+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [running]> on host 805e8d5936d1
[2024-04-12T00:31:32.461+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas1_no2' AIRFLOW_CTX_TASK_ID='check_even_odd' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:29:20.868171+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T00:29:20.868171+00:00'
[2024-04-12T00:31:32.463+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T00:31:32.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T00:31:32.504+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nomer2_dag.py", line 17, in check_even_odd
    if jumlah % 2 == 0:
       ~~~~~~~^~~
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
[2024-04-12T00:31:32.523+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas1_no2, task_id=check_even_odd, execution_date=20240412T002920, start_date=20240412T003132, end_date=20240412T003132
[2024-04-12T00:31:32.548+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task check_even_odd (unsupported operand type(s) for %: 'NoneType' and 'int'; 270)
[2024-04-12T00:31:32.580+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T00:31:32.606+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T00:31:32.616+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
