[2024-04-13T15:53:09.611+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-13T15:53:09.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas2.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T15:53:09.904+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas2.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T15:53:09.914+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-13T15:53:10.022+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-12 00:00:00+00:00
[2024-04-13T15:53:10.109+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-13T15:53:10.147+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2024-04-13T15:53:10.146+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas2', 'write_to_csv', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/prioritas2_dag.py', '--cfg-path', '/tmp/tmp1lay78yh']
[2024-04-13T15:53:10.170+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask write_to_csv
[2024-04-13T15:53:10.728+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas2.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [running]> on host a8c8062a752a
[2024-04-13T15:53:11.958+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas2' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-13T15:53:12.000+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-13T15:53:12.003+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-13T15:53:12.009+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_csv() missing 1 required positional argument: 'data'
[2024-04-13T15:53:12.853+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas2, task_id=write_to_csv, execution_date=20240412T000000, start_date=20240413T155309, end_date=20240413T155312
[2024-04-13T15:53:14.331+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 210 for task write_to_csv (write_to_csv() missing 1 required positional argument: 'data'; 180)
[2024-04-13T15:53:14.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-13T15:53:14.452+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-13T15:53:14.458+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
