[2024-04-12T11:43:16.212+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T11:43:16.279+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas2.write_to_txt manual__2024-04-12T11:33:02.825562+00:00 [queued]>
[2024-04-12T11:43:16.297+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas2.write_to_txt manual__2024-04-12T11:33:02.825562+00:00 [queued]>
[2024-04-12T11:43:16.298+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 9
[2024-04-12T11:43:16.331+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_txt> on 2024-04-12 11:33:02.825562+00:00
[2024-04-12T11:43:16.340+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T11:43:16.343+0000] {standard_task_runner.py:63} INFO - Started process 316 to run task
[2024-04-12T11:43:16.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas2', 'write_to_txt', 'manual__2024-04-12T11:33:02.825562+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/prioritas2_dag.py', '--cfg-path', '/tmp/tmpjevbfzw3']
[2024-04-12T11:43:16.350+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask write_to_txt
[2024-04-12T11:43:16.455+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas2.write_to_txt manual__2024-04-12T11:33:02.825562+00:00 [running]> on host 805e8d5936d1
[2024-04-12T11:43:16.552+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas2' AIRFLOW_CTX_TASK_ID='write_to_txt' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T11:33:02.825562+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T11:33:02.825562+00:00'
[2024-04-12T11:43:16.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T11:43:16.554+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T11:43:16.555+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_txt() missing 1 required positional argument: 'data'
[2024-04-12T11:43:16.563+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas2, task_id=write_to_txt, execution_date=20240412T113302, start_date=20240412T114316, end_date=20240412T114316
[2024-04-12T11:43:16.586+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 125 for task write_to_txt (write_to_txt() missing 1 required positional argument: 'data'; 316)
[2024-04-12T11:43:16.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T11:43:16.625+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T11:43:16.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
