[2024-04-12T00:39:25.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T00:39:25.275+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [queued]>
[2024-04-12T00:39:25.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [queued]>
[2024-04-12T00:39:25.285+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 8
[2024-04-12T00:39:25.304+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_even_odd> on 2024-04-12 00:29:20.868171+00:00
[2024-04-12T00:39:25.313+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=386) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T00:39:25.314+0000] {standard_task_runner.py:63} INFO - Started process 388 to run task
[2024-04-12T00:39:25.314+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas1_no2', 'check_even_odd', 'manual__2024-04-12T00:29:20.868171+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/nomer2_dag.py', '--cfg-path', '/tmp/tmp1j7hspf7']
[2024-04-12T00:39:25.317+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask check_even_odd
[2024-04-12T00:39:25.367+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas1_no2.check_even_odd manual__2024-04-12T00:29:20.868171+00:00 [running]> on host 805e8d5936d1
[2024-04-12T00:39:25.491+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas1_no2' AIRFLOW_CTX_TASK_ID='check_even_odd' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:29:20.868171+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T00:29:20.868171+00:00'
[2024-04-12T00:39:25.493+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T00:39:25.503+0000] {logging_mixin.py:188} INFO - Error: 'jumlah' memiliki nilai None atau tidak valid.
[2024-04-12T00:39:25.504+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-12T00:39:25.505+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T00:39:25.514+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=prioritas1_no2, task_id=check_even_odd, execution_date=20240412T002920, start_date=20240412T003925, end_date=20240412T003925
[2024-04-12T00:39:25.569+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-12T00:39:25.594+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T00:39:25.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
